version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=200h"
    networks:
      - monitoring
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/blackbox_targets_2xx.yml:/etc/prometheus/blackbox_targets_2xx.yml
      - ./config/alertrules.yml:/etc/prometheus/alertrules.yml
    ports:
      - 9090:9090

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: unless-stopped
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    networks:
      - monitoring
    volumes:
      - ./config/blackbox.yml:/etc/blackbox/blackbox.yml
#
#  alertmanager:
#    image: prom/alertmanager:latest
#    container_name: alertmanager
#    restart: unless-stopped
#    command:
#      - "--config.file=/etc/alertmanager/alertmanager.yml"
#      - "--storage.path=/alertmanager"
#    networks:
#      - monitoring
#    volumes:
#      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    networks:
      - monitoring
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/tls/cer.cer:/etc/pki/tls/certs/cer.cer
      - ./config/nginx/tls/key.key:/etc/pki/tls/certs/key.key
    ports:
      - 80:80
      - 443:443

networks:
  monitoring: {}

volumes:
  prometheus_data: {}
  grafana_data: {}
