- targets:
  - "https://banki.ru"
  - "https://ura.news"
  - "https://belstat.gov.by"
  - "https://aif.ru"
  - "https://customs.gov.by"
  - "https://nca.by"
  - "https://legat.by"
  - "https://bsca.by"
  - "https://etalonline.by"
  - "https://economy.gov.by"
  - "https://mintrud.gov.by"
  - "https://ncpi.gov.by"
  - "https://tsouz.belgiss.by"
  - "https://rceth.by"
  - "https://vedomosti.ru"
  - "https://belkart.by"
  - "https://absolutbank.by"
  - "https://belveb.by"
  - "https://belarus.by"
  - "https://vtb.by"
  - "https://rbank.by"
  - "https://belapb.by"
  - "https://belgazprombank.by"
  - "https://belinvestbank.by"
  - "https://belarusbank.by"
  - "https://bnb.by"
  - "https://bsb.by"
  - "https://mtbank.by"
  - "https://vtb.ru"
  - "https://sberbank.ru"
  - "https://gazprombank.ru"
  - "https://absolutbank.ru"
  - "https://bspb.ru"
  - "https://ubrr.ru"
  - "https://rzd.ru"
  - "https://avangard.ru"
  - "https://domrfbank.ru"
  - "https://moex.com"
  - "https://online.gpb.ru"
  - "https://mkb.ru"
  - "https://vnukovo.ru"
  - "https://svo.aero"
  - "https://dme.ru"
  - "https://aeroportdomodedovo.ru"
  - "https://zia.aero"
  - "https://ostafyevo.gazprom.ru"
  - "https://pulkovoairport.ru"
  - "https://airport-rzhevka.ru"
  - "https://rov.aero"
  - "https://krr.aero"
  - "https://gdz.aero"
  - "https://simferopol-airport.ru"
  - "https://svx.aero"
  - "https://yoomoney.ru"
  - "https://qiwi.com"
  - "https://tinkoff.ru"
  - "https://mironline.ru"
  - "https://rsb.ru"
  - "https://alfabank.ru"
  - "https://rncb.ru"
  - "https://pochtabank.ru"
  - "https://cbr.ru"
  - "https://raiffeisen.ru"
  - "https://nspk.ru"
  - "https://spvb.ru"
  - "https://rosbank.ru"
  - "https://unicreditbank.ru"
  - "https://abr.ru"
  - "https://vbrr.ru"
  - "https://btabank.by"
  - "https://belavia.by"
  - "https://poezd.ru"
  - "https://vokzalbelgorod.ru"
  - "https://vokzalkursk.ru"
  - "https://vokzalrostov.ru"
  - "https://rostov.dzvr.ru"
  - "https://voronezh.rusavtobus.ru"
  - "https://bus46.ru"
  - "https://avtovokzal31.ru"
  - "https://busfor.ru"
  - "https://goonbus.ru"
  - "https://krasnodar1.ru"
  - "https://rfbus.ru"
  - "https://russia.poezda.net"
  - "https://avtovokzaly.ru"
  - "https://poezda.net"
  - "https://tagancity.ru"
  - "https://taghospital.ru"
  - "https://tutu.ru"
  - "https://tagmed1.ru"
  - "https://taganrog-gbsmp.ru"
  - "https://tgb3.ru"
  - "https://marmeladmall.ru"
  - "https://letomall.su"
  - "https://iecp.ru/ep/ep-verification"
  - "https://iecp.ru/ep/uc-list"
  - "https://uc-osnovanie.ru"
  - "https://nucrf.ru"
  - "https://belinfonalog.ru"
  - "https://roseltorg.ru"
  - "https://astralnalog.ru"
  - "https://nwudc.ru"
  - "https://center-inform.ru"
  - "https://kk.bank/UdTs"
  - "https://structure.mil.ru/structure/uc/info.htm"
  - "https://ucpir.ru"
  - "https://dreamkas.ru"
  - "https://e-portal.ru"
  - "https://izhtender.ru"
  - "https://imctax.parus-s.ru"
  - "https://icentr.ru"
  - "https://kartoteka.ru"
  - "https://rsbis.ru/elektronnaya-podpis"
  - "https://stv-it.ru"
  - "https://crypset.ru"
  - "https://kt-69.ru"
  - "https://24ecp.ru"
  - "https://kraskript.com"
  - "https://ca.ntssoft.ru"
  - "https://y-center.ru"
  - "https://rcarus.ru"
  - "https://rk72.ru"
  - "https://squaretrade.ru"
  - "https://ca.gisca.ru"
  - "https://otchet-online.ru"
  - "https://udcs.ru"
  - "https://cit-ufa.ru"
  - "https://elkursk.ru"
  - "https://icvibor.ru"
  - "https://ucestp.ru"
  - "https://mcspro.ru"
  - "https://infotrust.ru"
  - "https://epnow.ru"
  - "https://ca.kamgov.ru"
  - "https://mascom-it.ru"
  - "https://cfmc.ru"
  - "https://belta.by"
  - "https://sputnik.by"
  - "https://tvr.by"
  - "https://sb.by"
  - "https://belmarket.by"
  - "https://belarus24.by"
  - "https://ont.by"
  - "https://024.by"
  - "https://belnovosti.by"
  - "https://mogilevnews.by"
  - "https://mil.by"
  - "https://slonves.by"
  - "https://ctv.by"
  - "https://radiobelarus.by"
  - "https://radiusfm.by"
  - "https://alfaradio.by"
  - "https://radiomir.by"
  - "https://radiostalica.by"
  - "https://radiobrestfm.by"
  - "https://tvrmogilev.by"
  - "https://minsknews.by"
  - "https://zarya.by"
  - "https://grodnonews.by"
  - "https://rec.gov.by/ru"
  - "https://government.by"
  - "https://president.gov.by/ru"
  - "https://mvd.gov.by/ru"
  - "https://kgb.by/ru"
  - "https://prokuratura.gov.by"
  - "https://nbrb.by"
  - "https://brrb.by"
  - "https://bankdabrabyt.by"
  - "https://belinvestbank.by/individual"
  - "https://bgp.by/ru"
  - "https://belneftekhim.by"
  - "https://bellegprom.by"
  - "https://energo.by"
  - "https://belres.by/ru"
  - "https://kgb.by/ru/"
  - "https://ria.ru"
  - "https://gazeta.ru"
  - "https://kp.ru"
  - "https://riafan.ru"
  - "https://pikabu.ru"
  - "https://kommersant.ru"
  - "https://mk.ru"
  - "https://yaplakal.com"
  - "https://rbc.ru"
  - "https://bezformata.com"
  - "https://mail.rkn.gov.ru"
  - "https://cloud.rkn.gov.ru"
  - "https://mvd.gov.ru"
  - "https://pwd.wto.economy.gov.ru"
  - "https://stroi.gov.ru"
  - "https://proverki.gov.ru"
  - "https://gazprom.ru"
  - "https://lukoil.ru"
  - "https://magnit.ru"
  - "https://nornickel.com"
  - "https://surgutneftegas.ru"
  - "https://tatneft.ru"
  - "https://evraz.com/ru"
  - "https://nlmk.com"
  - "https://sibur.ru"
  - "https://severstal.com"
  - "https://metalloinvest.com"
  - "https://nangs.org"
  - "https://rmk-group.ru/ru"
  - "https://tmk-group.ru"
  - "https://polymetalinternational.com/ru"
  - "https://uralkali.com/ru"
  - "https://eurosib.ru"
  - "https://omk.ru"
  - "https://gosuslugi.ru"
  - "https://mos.ru/uslugi"
  - "https://kremlin.ru"
  - "https://government.ru"
  - "https://mil.ru"
  - "https://nalog.gov.ru"
  - "https://customs.gov.ru"
  - "https://pfr.gov.ru"
  - "https://rkn.gov.ru"
  - "https://cleanbtc.ru"
  - "https://bonkypay.com"
  - "https://changer.club"
  - "https://superchange.net"
  - "https://mine.exchange"
  - "https://platov.co"
  - "https://ww-pay.net"
  - "https://delets.cash"
  - "https://betatransfer.org"
  - "https://ramon.money"
  - "https://coinpaymaster.com"
  - "https://bitokk.biz"
  - "https://www.netex24.net"
  - "https://cashbank.pro"
  - "https://flashobmen.com"
  - "https://abcobmen.com"
  - "https://ychanger.net"
  - "https://multichange.net"
  - "https://24paybank.ne"
  - "https://royal.cash"
  - "https://prostocash.com"
  - "https://baksman.org"
  - "https://kupibit.me"