global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: "docker-host"

rule_files:
  - alertrules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_basic_auth_2xx]
    static_configs:
      - targets:
      {{ range (split .Env.TARGETS ",") }}  - "{{ . }}"
      {{ end }}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox:9115

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
